spring:
  cloud:
    gateway:
#      #可以根据请求参数,cookie,host,请求时间,请求头等进行校验判断路由, 下面根据先后顺序转发
#      routes:
#        - id: host_route
#          uri: http://httpbin.org:80/get
#          predicates:
#            - Path=/zzzgd/** # 请求地址携带zzzgd的,则转发
      discovery:
        locator:
          # 是否可以通过其他服务的serviceId来转发给具体的服务实例。默认为false
          # 为true,自动创建路由,路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问
          enabled: false